import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  courseSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Phase 1 — Web Foundations',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Module 01 — HTML, Git & CSS',
          items: [
            'module-01/overview',
            'module-01/html-fundamentals',
            'module-01/git-workflow',
            'module-01/css-foundations',
            'module-01/css-layout',
            'module-01/challenge',
          ],
        },
        {
          type: 'category',
          label: 'Module 02 — Tailwind CSS',
          items: [
            'module-02/overview',
            'module-02/tailwind-setup',
            'module-02/utility-classes',
            'module-02/responsive-design',
            'module-02/dark-mode',
            'module-02/custom-components',
            'module-02/challenge',
          ],
        },
        {
          type: 'category',
          label: 'Module 03 — JavaScript ES2024+',
          items: [
            'module-03/overview',
            'module-03/variables-types',
            'module-03/functions-scope',
            'module-03/arrays-objects',
            'module-03/async-javascript',
            'module-03/modules-esm',
            'module-03/challenge',
          ],
        },
        {
          type: 'category',
          label: 'Module 04 — TypeScript Fundamentals',
          items: [
            'module-04/overview',
            'module-04/why-typescript',
            'module-04/types-interfaces',
            'module-04/generics',
            'module-04/utility-types',
            'module-04/tsconfig',
            'module-04/challenge',
          ],
        },
        {
          type: 'category',
          label: 'Module 05 — Web APIs (No jQuery)',
          items: [
            'module-05/overview',
            'module-05/dom-manipulation',
            'module-05/events',
            'module-05/fetch-api',
            'module-05/localstorage-indexeddb',
            'module-05/challenge',
          ],
        },
        {
          type: 'category',
          label: 'Module 06 — Server-Side APIs',
          items: [
            'module-06/overview',
            'module-06/rest-fundamentals',
            'module-06/fetch-async-await',
            'module-06/error-handling',
            'module-06/api-design',
            'module-06/challenge',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Project 1 — Front-End Application',
      items: ['project-01/overview', 'project-01/requirements', 'project-01/rubric'],
    },
    {
      type: 'category',
      label: 'Phase 2 — Node.js Backend',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Module 07 — Node.js + TypeScript',
          items: [
            'module-07/overview',
            'module-07/node-fundamentals',
            'module-07/typescript-node',
            'module-07/file-system',
            'module-07/npm-packages',
            'module-07/challenge',
          ],
        },
        {
          type: 'category',
          label: 'Module 08 — OOP with TypeScript',
          items: [
            'module-08/overview',
            'module-08/classes-interfaces',
            'module-08/inheritance-polymorphism',
            'module-08/design-patterns',
            'module-08/testing-vitest',
            'module-08/challenge',
          ],
        },
        {
          type: 'category',
          label: 'Module 09 — Express 5 + REST APIs',
          items: [
            'module-09/overview',
            'module-09/express-setup',
            'module-09/routing',
            'module-09/middleware',
            'module-09/error-handling',
            'module-09/rest-conventions',
            'module-09/challenge',
          ],
        },
        {
          type: 'category',
          label: 'Module 10 — PostgreSQL & SQL',
          items: [
            'module-10/overview',
            'module-10/databases-intro',
            'module-10/sql-fundamentals',
            'module-10/joins-relations',
            'module-10/indexes-performance',
            'module-10/challenge',
          ],
        },
        {
          type: 'category',
          label: 'Module 11 — Prisma ORM',
          items: [
            'module-11/overview',
            'module-11/prisma-setup',
            'module-11/schema-models',
            'module-11/crud-operations',
            'module-11/relations',
            'module-11/migrations',
            'module-11/challenge',
          ],
        },
        {
          type: 'category',
          label: 'Module 12 — Authentication & Security',
          items: [
            'module-12/overview',
            'module-12/jwt-auth',
            'module-12/bcrypt-hashing',
            'module-12/auth-middleware',
            'module-12/refresh-tokens',
            'module-12/challenge',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Project 2 — Full-Stack REST App',
      items: ['project-02/overview', 'project-02/requirements', 'project-02/rubric'],
    },
    {
      type: 'category',
      label: 'Phase 3 — CS + Advanced Backend',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Module 13 — Computer Science Fundamentals',
          items: [
            'module-13/overview',
            'module-13/big-o-notation',
            'module-13/data-structures',
            'module-13/sorting-algorithms',
            'module-13/recursion',
            'module-13/challenge',
          ],
        },
        {
          type: 'category',
          label: 'Module 14 — MongoDB & Mongoose',
          items: [
            'module-14/overview',
            'module-14/mongodb-intro',
            'module-14/mongoose-schemas',
            'module-14/crud-aggregations',
            'module-14/when-to-use-nosql',
            'module-14/challenge',
          ],
        },
        {
          type: 'category',
          label: 'Module 15 — NestJS',
          items: [
            'module-15/overview',
            'module-15/nest-architecture',
            'module-15/modules-controllers-services',
            'module-15/dependency-injection',
            'module-15/guards-pipes',
            'module-15/prisma-integration',
            'module-15/challenge',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Phase 4 — Modern Frontend',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Module 16 — React + TypeScript',
          items: [
            'module-16/overview',
            'module-16/vite-setup',
            'module-16/components-jsx',
            'module-16/state-hooks',
            'module-16/react-query',
            'module-16/react-router',
            'module-16/challenge',
          ],
        },
        {
          type: 'category',
          label: 'Module 17 — Next.js App Router',
          items: [
            'module-17/overview',
            'module-17/app-router',
            'module-17/server-components',
            'module-17/data-fetching',
            'module-17/server-actions',
            'module-17/nextauth',
            'module-17/challenge',
          ],
        },
        {
          type: 'category',
          label: 'Module 18 — tRPC & Type-Safe APIs',
          items: [
            'module-18/overview',
            'module-18/trpc-setup',
            'module-18/routers-procedures',
            'module-18/client-integration',
            'module-18/vs-graphql',
            'module-18/challenge',
          ],
        },
        {
          type: 'category',
          label: 'Module 19 — State Management with Zustand',
          items: [
            'module-19/overview',
            'module-19/zustand-basics',
            'module-19/async-actions',
            'module-19/devtools-persist',
            'module-19/vs-context-api',
            'module-19/challenge',
          ],
        },
        {
          type: 'category',
          label: 'Module 20 — PWA & Performance',
          items: [
            'module-20/overview',
            'module-20/pwa-fundamentals',
            'module-20/service-workers',
            'module-20/vite-pwa',
            'module-20/performance-audit',
            'module-20/challenge',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Phase 5 — Production & Deployment',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Module 21 — CI/CD & DevOps Basics',
          items: [
            'module-21/overview',
            'module-21/github-actions',
            'module-21/docker-basics',
            'module-21/environment-variables',
            'module-21/challenge',
          ],
        },
        {
          type: 'category',
          label: 'Module 22 — Deployment',
          items: [
            'module-22/overview',
            'module-22/vercel-nextjs',
            'module-22/railway-nest',
            'module-22/supabase-postgres',
            'module-22/monitoring',
            'module-22/challenge',
          ],
        },
        {
          type: 'category',
          label: 'Module 23 — AI Integration',
          items: [
            'module-23/overview',
            'module-23/claude-api',
            'module-23/streaming-responses',
            'module-23/tool-use',
            'module-23/challenge',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Capstone Project',
      items: [
        'capstone/overview',
        'capstone/requirements',
        'capstone/tech-stack',
        'capstone/rubric',
      ],
    },
  ],
};

export default sidebars;
